name: 'financas_data_pipeline'
version: '1.0'
profile: 'financas_data'
config-version: 2

# Caminhos para as pastas de recursos
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

# Diretório de saída
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

# Configuração de modelos
models:
  financas_data_pipeline:
    +schema: null  # Evita o comportamento padrão de concatenar prefixos
    +database: "{{ env_var('DBT_DATABASE') }}"
    
    prata:
      +schema: "prata"  # Esquema existente no banco
      +database: "{{ env_var('DBT_DATABASE') }}"
      +materialized: incremental
      +tags: ["prata"]

    ouro:
      +schema: "ouro"  # Esquema existente no banco
      +database: "{{ env_var('DBT_DATABASE') }}"
      +tags: ["ouro"]
