version: 2

models:
  - name: portfolio
    schema: ouro
    description: "Tabela consolidada com informações de ativos financeiros, indicadores técnicos e rendimento do Tesouro."
    columns:
      - name: data
        description: "Data do registro."
      - name: ativo
        description: "Código do ativo."
      - name: preco_abertura
        description: "Preço de abertura do ativo no dia."
      - name: preco_alto
        description: "Preço mais alto do ativo no dia."
      - name: preco_baixo
        description: "Preço mais baixo do ativo no dia."
      - name: preco_fechamento
        description: "Preço de fechamento do ativo no dia."
      - name: volume_negociado
        description: "Volume total de negociações do ativo no dia."
      - name: indicador
        description: "Nome do indicador técnico."
      - name: valor_indicador
        description: "Valor do indicador técnico para o ativo no dia."
      - name: rendimento_tesouro
        description: "Rendimento do Tesouro no dia."
