name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SQLALCHEMY_WARN_20: "1"
      SQLALCHEMY_SILENCE_UBER_WARNING: "1"
      CHAVE_API: ${{ secrets.CHAVE_API }}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Create temporary directories for testing
      run: mkdir -p /tmp/bronze

    - name: Set environment variable for temporary directory
      run: echo "CAMINHO_BRONZE=/tmp/bronze" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest tests/ --disable-warnings
